### ISSUE TITLE
Centering a text doesn't work in live preview

### ISSUE THREAD

**Issue by sizhky** [LilaRest/obsidian-custom-classes#13]
**Describe the bug**
Using "text-align: center" does not align the the text to center

**To Reproduce**
1. Add to `custom.css` the following class
```css
.centered-text {
  text-align: center !important;
  background-color: rgba(200, 233, 22, 1.0);
}
```
2. Add the text ``this is my random text `class: centered-text` ``
3. The text is coloured as expected but not in the center but this happens only in live-preview

**Expected behavior**
The text should be coloured and in the center in live preview

**Screenshots**

<img width="412" alt="image" src="https://user-images.githubusercontent.com/3656100/235305493-4a3a9f81-bfd1-4033-a4d7-d7a3f9f8d986.png">

**Device (please complete the following information):**
 - Operating System: MacOS
 - Obsidian version: v1.1.16

**Comment by LilaRest** [comment]
Hi @sizhky ! Thanks for reporting this bug. Unfortunately I'm not maintaining this repository anymore as I don't use it anymore.
(was using it for frontmatter, but have replaced it by callouts, see [here](https://forum.obsidian.md/t/a-frontmatter-that-finally-supports-links-lilas-frontmatter/53087))

However, I'll be happy to accept any contributions, so feel free to PR :)

**Comment by sizhky** [comment]
Thanks for responding. Unfortunately I'm a noob in javascript and moreso developing something for obsidian. Could you maybe give me a couple of pointers on where to look at for me to get started on a possible solution?

**Comment by LilaRest** [comment]
> Thanks for responding. Unfortunately I'm a noob in javascript and moreso developing something for obsidian. Could you maybe give me a couple of pointers on where to look at for me to get started on a possible solution?

@sizhky After looking to your problem more carefully, I'm pretty sure you can find a workaround without having to get your hands in JS ! :D

Firstly, on my side it works well:
![image](https://user-images.githubusercontent.com/48853371/235370235-d32328ed-3075-45f2-90a2-20e60cc921ff.png)

As you can see, the background color reveals that the `<p>` element that contains the text is taking the whole note width, which for some reasons is not the case on your side.

I can't pinpoint the problem without going through all the CSS declarations applied to this line of your note, but here is a possible workaround:
```css
.centered-text {
  display: block;
  width: 100%; /* Maybe display block is already enough ? */
  text-align: center !important;
  background-color: rgba(200, 233, 22, 1.0);
}
```
